basic_dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /home/gesogeso/ghq/github.com/dagster-io/basic-dbt-project/dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: /home/gesogeso/ghq/github.com/dagster-io/basic-dbt-project/prod.duckdb
      threads: 4
